### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by ltworf** [Pipoline/rocket-python#27]
Hello,

At my work they created an instance of rc integrated with microsoft office, so I don't have a regular username and password.

It'd be better to be able to also accept the token directly.

**Comment by pipozzz** [comment]
Hello,
this is good idea, I will add  this feature to the next milestone.
Thanks

**Comment by ltworf** [comment]
Good thing I gave up using this library then

**Comment by pipozzz** [comment]
I was very busy, so I’ll definitely add this feature.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
