### ISSUE TITLE
No module named 'rocketchat' during api call

### ISSUE THREAD

**Issue by TheoRice** [Pipoline/rocket-python#40]
Started a test application that just copies the code in the "usage" section of the readme. 

Running python 3, I get the error message "No module named 'rocketchat'"

Running python 2, I get "No handlers could be found for logger "rocketchat.calls.base""

Any ideas why those would pop up?

**Comment by pipozzz** [comment]
How exactly you installed package and how you run tour app? it seems you installed package to python2 and you want run python3 where this package is not there

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pipozzz** [comment]
Any luck so far?

**Comment by pipozzz** [comment]
Closing this issue due to no response from your side. If you encounter any other issue just reopen it.
