### ISSUE TITLE
create_user returns 400 error

### ISSUE THREAD

**Issue by ard9000** [Pipoline/rocket-python#44]
All of the other API calls work fine. 

HTTPError: 400 Client Error: Bad Request for url: https://chat.mychatserver.com/api/v1/users.create

**Comment by pipozzz** [comment]
Could you give us more info about your environemnt? What version of rocket.chat you are using ? What payload you are sending ?

**Comment by mmehrle** [comment]
Hi there - I work with ard900. We are both using OS X and installed the latest version of rocket-python (fresh install via pip).

Here's the code (with passwords and URLs altered):

```python
from rocketchat.api import RocketChatAPI

def send_rc_message(api, message):
    api.send_message(message, 'expected_move_breakouts')

def init_rocket_chat():
    api = RocketChatAPI(settings={'username': 'xxx@xxxxxxxx.com', 'password': 'XXXXXXX',
                                    'domain': 'https://chat.xxxxxxxxx.com'})
    return api

api = init_rocket_chat()

def add_user(api, email, name, password, username):
    api.create_user('email', 
                    'name', 
                    'password', 
                    'username', 
                     active=True, 
                     roles=['user'], 
                     join_default_channels=True, 
                     require_password_change=False, 
                     send_welcome_email=False, 
                     verified=False, 
                     customFields=None)

add_user(api, 'xxxxxx@gmail.com','Ard9','12344321XX','secret-password')
```

**Output:**

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-6-2248617d95f8> in <module>()
----> 1 add_user(api, 'xxxxxx@gmail.com','Ard9','12344321XX','secret-password')

<ipython-input-5-be57da95c620> in add_user(api, email, name, password, username)
     11                      send_welcome_email=False,
     12                      verified=False,
---> 13                      customFields=None)

/Users/michael/anaconda3/lib/python3.6/site-packages/rocketchat/api.py in create_user(self, email, name, password, username, **kwargs)
    220             password=password,
    221             username=username,
--> 222             **kwargs
    223         )
    224 

/Users/michael/anaconda3/lib/python3.6/site-packages/rocketchat/calls/base.py in call(self, *args, **kwargs)
    115         ))
    116 
--> 117         result.raise_for_status()
    118         self.logoff()
    119 

/Users/michael/anaconda3/lib/python3.6/site-packages/requests/models.py in raise_for_status(self)
    938 
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 
    942     def close(self):

HTTPError: 400 Client Error: Bad Request for url: https://chat.XXXXXXX.com/api/v1/users.create

**Comment by pipozzz** [comment]
First problem which I see is using constant string instead of function parameters here:

```python
def add_user(api, email, name, password, username):
    api.create_user('email',  # <- here
                    'name',  # <- here
                    'password', # <- here
                    'username', # <- here
                     active=True, 
                     roles=['user'], 
                     join_default_channels=True, 
                     require_password_change=False, 
                     send_welcome_email=False, 
                     verified=False, 
                     customFields=None)
```

**Comment by mmehrle** [comment]
Yeah I can't believe we both didn't see that - LOL - that's what copy/paste gets you :-)

Fixed it:

`def add_user(api, email, name, password, username):
    api.create_user(email, 
                    name, 
                    password, 
                    username, 
                    active=True, 
                    roles=['user'], 
                    join_default_channels=True, 
                    require_password_change=False, 
                    send_welcome_email=False, 
                    verified=False, 
                    customFields=None)`

but it's still throwing the same error for some reason:

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-5-2248617d95f8> in <module>()
----> 1 add_user(api, 'xxxxx@gmail.com','xxxx','xxxxxx','xxxxx')

<ipython-input-4-7072c5cee4f9> in add_user(api, email, name, password, username)
     10                     send_welcome_email=False,
     11                     verified=False,
---> 12                     customFields=None)

/Users/michael/anaconda3/lib/python3.6/site-packages/rocketchat/api.py in create_user(self, email, name, password, username, **kwargs)
    220             password=password,
    221             username=username,
--> 222             **kwargs
    223         )
    224 

/Users/michael/anaconda3/lib/python3.6/site-packages/rocketchat/calls/base.py in call(self, *args, **kwargs)
    115         ))
    116 
--> 117         result.raise_for_status()
    118         self.logoff()
    119 

/Users/michael/anaconda3/lib/python3.6/site-packages/requests/models.py in raise_for_status(self)
    938 
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 
    942     def close(self):

HTTPError: 400 Client Error: Bad Request for url: https://chat.xxxxxxxx.com/api/v1/users.create

**Comment by mmehrle** [comment]
Hi again - it seems you may have misunderstood my latest response. The problem persists even though I fixed the params. Can you please take another look?

**Comment by pipozzz** [comment]
Just change `customFields=None` to `customFields={}` it seems new version of rocketchat do not support None type, I will fix this today or so.

**Comment by pipozzz** [comment]
It's already fixed so from now you can avoid setting customFields if you don't use it. If you have any problem just reopen this issue or create new one.
Thanks

**Comment by mmehrle** [comment]
Yes that worked - thanks a lot for fixing this!

**Comment by warriorbik** [comment]
I've the similar problem when using the create_user api.

`api.create_user('xxxx@kodiary.com','xxx','xxxx','xxxx',
                        active=True, roles=['user'],join_default_channels=False, require_password_change=False,
                        send_welcome_email=True, verified=False, customFields={})`
The error is same when removing customFields and using customFields=None.
HTTPError: 400 Client Error: Bad Request for url: https://chat.kodiary.com/api/v1/users.create

Where as from the logs of rocket chat on my server shows:

{"level":35,"time":"2022-02-18T05:09:11.600Z","pid":8,"hostname":"036b252e8186","name":"","name":"API","method":"POST","url":"/api/v1/login","userAgent":"python-requests/2.27.1","length":"29","host":"chat.kodiary.com","remoteIP":"27.34.22.180","responseTime":159} 
{"level":35,"time":"2022-02-18T05:09:12.778Z","pid":8,"hostname":"036b252e8186","name":"","name":"API","method":"POST","url":"/api/v1/users.create","userId":"u7nopRH2ZfBieBk83","userAgent":"python-requests/2.27.1","length":"256","host":"chat.kodiary.com","remoteIP":"27.34.22.180","err":{"type":"errorClass","message":"Match error: Missing key 'email'","stack":"Error: Match error: Missing key 'email'<br>    at check (packages/check/match.js:36:17)<br>    at Object.post (app/api/server/v1/users.js:36:4)<br>    at app/api/server/api.js:425:96<br>    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)<br>    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:425:39)<br>    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)<br>    at packages/rocketchat_restivus/lib/route.coffee:59:33<br>    at packages/simple_json-routes.js:100:9","path":"","sanitizedError":{"type":"errorClass","message":"Match failed [400]","stack":"Error: Match failed [400]<br>    at errorClass.<anonymous> (packages/check/match.js:91:27)<br>    at new errorClass (packages/meteor.js:660:17)<br>    at check (packages/check/match.js:36:17)<br>    at Object.post (app/api/server/v1/users.js:36:4)<br>    at app/api/server/api.js:425:96<br>    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)<br>    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:425:39)<br>    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)<br>    at packages/rocketchat_restivus/lib/route.coffee:59:33<br>    at packages/simple_json-routes.js:100:9","isClientSafe":true,"error":400,"reason":"Match failed","errorType":"Meteor.Error"},"errorType":"Match.Error"},"status":400,"responseTime":11,"msg":"Match error: Missing key 'email'"} 
{"level":35,"time":"2022-02-18T05:09:18.556Z","pid":8,"hostname":"036b252e8186","name":"","name":"API","method":"POST","url":"/api/v1/method.call/license:getModules","userId":"wyQNrrLLPaWRoTsDE","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36","length":"96","host":"chat.kodiary.com","remoteIP":"27.34.22.180","status":200,"responseTime":4}

**Comment by opensworup** [comment]
@pipozzz Can you update the documentation to create new users. Right now it has customFields=None. It should be customFields={} .

**Comment by pipozzz** [comment]
Thanks for letting me know, I'll fix this soon
