### ISSUE TITLE
which python wrapper to use? rocketchat_API or rocket-python

### ISSUE THREAD

**Issue by xu4wang** [Pipoline/rocket-python#47]
Dear All,

I'm new to RocketChat, looking for a python SDK for developing RocketChat bot.  I found two:

- https://github.com/jadolg/rocketchat_API
- https://github.com/Pipoline/rocket-python

Do you know which I should I choose? what's the difference?

Thanks in advance,
Austin

**Comment by pipozzz** [comment]
I would say it's based on taste

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
