### ISSUE TITLE
Attachments in message payload

### ISSUE THREAD

**Issue by JargeZ** [Pipoline/rocket-python#48]
**Is your feature request related to a problem? Please describe.**
Hi, I ran into a problem that I could not find how to send an attachment, which is described by the endpoint in api rocketchat [here](https://docs.rocket.chat/guides/developer-guides/rest-api/chat/postmessage#attachments-detail)

**Describe the solution you'd like**
Implement the necessary keys from the api documentation, which are described [here](https://docs.rocket.chat/guides/developer-guides/rest-api/chat/postmessage#payload) in the send_message method with the correct payload build

**Describe alternatives you've considered**
I looked at the methods that are in the api class. File upload implemented, I saw issue #22 on this
However, I did not find the possibility of creating my own attachment

P.S.
I just started using this module, so if this feature is available, then I apologize, but I think it will be good if it is described explicitly here.
If it is not implemented yet, then I will probably be able to someday make a PR for this, if I use this module for my integrations. And when I figure out the code and structure.

In any case, I want to hear your comment about this feature.

Thank you!

**Comment by soundstorm** [comment]
The `upload_file` method is even mentioned in the readme

**Comment by GrabsOrion** [comment]
+1 to @JargeZ request.
Upload method is irrelevant since you can't view image preview with it.
This feature only available if you send an image in the postMessage payload.
