### ISSUE TITLE
400 error when using the create_user api.

### ISSUE THREAD

**Issue by warriorbik** [Pipoline/rocket-python#58]
I've the similar problem when using the create_user api.

`api.create_user('xxxx@kodiary.com','xxx','xxxx','xxxx',
                        active=True, roles=['user'],join_default_channels=False, require_password_change=False,
                        send_welcome_email=True, verified=False, customFields={})`
The error is same when removing customFields and using customFields=None.
HTTPError: 400 Client Error: Bad Request for url: https://chat.kodiary.com/api/v1/users.create

Where as from the logs of rocket chat on my server shows:

{"level":35,"time":"2022-02-18T05:09:11.600Z","pid":8,"hostname":"036b252e8186","name":"","name":"API","method":"POST","url":"/api/v1/login","userAgent":"python-requests/2.27.1","length":"29","host":"chat.kodiary.com","remoteIP":"27.34.22.180","responseTime":159} 
{"level":35,"time":"2022-02-18T05:09:12.778Z","pid":8,"hostname":"036b252e8186","name":"","name":"API","method":"POST","url":"/api/v1/users.create","userId":"u7nopRH2ZfBieBk83","userAgent":"python-requests/2.27.1","length":"256","host":"chat.kodiary.com","remoteIP":"27.34.22.180","err":{"type":"errorClass","message":"Match error: Missing key 'email'","stack":"Error: Match error: Missing key 'email'<br>    at check (packages/check/match.js:36:17)<br>    at Object.post (app/api/server/v1/users.js:36:4)<br>    at app/api/server/api.js:425:96<br>    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)<br>    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:425:39)<br>    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)<br>    at packages/rocketchat_restivus/lib/route.coffee:59:33<br>    at packages/simple_json-routes.js:100:9","path":"","sanitizedError":{"type":"errorClass","message":"Match failed [400]","stack":"Error: Match failed [400]<br>    at errorClass.<anonymous> (packages/check/match.js:91:27)<br>    at new errorClass (packages/meteor.js:660:17)<br>    at check (packages/check/match.js:36:17)<br>    at Object.post (app/api/server/v1/users.js:36:4)<br>    at app/api/server/api.js:425:96<br>    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)<br>    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:425:39)<br>    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)<br>    at packages/rocketchat_restivus/lib/route.coffee:59:33<br>    at packages/simple_json-routes.js:100:9","isClientSafe":true,"error":400,"reason":"Match failed","errorType":"Meteor.Error"},"errorType":"Match.Error"},"status":400,"responseTime":11,"msg":"Match error: Missing key 'email'"} 
{"level":35,"time":"2022-02-18T05:09:18.556Z","pid":8,"hostname":"036b252e8186","name":"","name":"API","method":"POST","url":"/api/v1/method.call/license:getModules","userId":"wyQNrrLLPaWRoTsDE","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36","length":"96","host":"chat.kodiary.com","remoteIP":"27.34.22.180","status":200,"responseTime":4}

_Originally posted by @warriorbik in https://github.com/Pipoline/rocket-python/issues/44#issuecomment-1043908408_

**Comment by pipozzz** [comment]
Confirming this, I'll try to open issue in rocketchat project

**Comment by pipozzz** [comment]
It seems that I found the issue, I'll inform you about fix

**Comment by pipozzz** [comment]
Fixed

**Comment by warriorbik** [comment]
Thank you, the issue with the email is fixed but now it shows type cast error for active:

`api.create_user(email, 
                    name, 
                    password, 
                    username, 
                    active=True, 
                    roles=['user'], 
                    join_default_channels=True, 
                    require_password_change=False, 
                    send_welcome_email=False, 
                    verified=False, 
                    customFields=None)`

API","method":"POST","url":"/api/v1/users.create","userId":"u7nopRH2ZfBieBk83","userAgent":"python-requests/2.27.1","length":"184","host":"chat.kodiary.com","remoteIP":"27.34.22.95","err":{"type":"errorClass","message":"Match error: Expected boolean, got string in field active","stack":"Error: Match error: Expected boolean, got string in field active<br>    at check (packages/check/match.js:36:17)<br>    at Object.post (app/api/server/v1/users.js:36:4)<br>    at app/api/server/api.js:425:96<br>    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)<br>    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:425:39)<br>    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)<br>    at packages/rocketchat_restivus/lib/route.coffee:59:33<br>    at packages/simple_json-routes.js:100:9","path":"active","sanitizedError":{"type":"errorClass","message":"Match failed [400]","stack":"Error: Match failed [400]<br>    at errorClass.<anonymous> (packages/check/match.js:91:27)<br>    at new errorClass (packages/meteor.js:660:17)<br>    at check (packages/check/match.js:36:17)<br>    at Object.post (app/api/server/v1/users.js:36:4)<br>    at app/api/server/api.js:425:96<br>    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)<br>    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:425:39)<br>    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)<br>    at packages/rocketchat_restivus/lib/route.coffee:59:33<br>    at packages/simple_json-routes.js:100:9","isClientSafe":true,"error":400,"reason":"Match failed","errorType":"Meteor.Error"},"errorType":"Match.Error"},"status":400,"responseTime":18,"msg":"Match error: Expected boolean, got string in field active"} 
{"level":35,"time":"2022-03-07T12:17:36.494Z","pid":8,"hostname":"036b252e8186","name":"","name":"API","method":"POST","url":"/api/v1/method.call/license:getModules","userId":"wyQNrrLLPaWRoTsDE","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36","length":"97","host":"chat.kodiary.com","remoteIP":"27.34.22.95","status":200,"responseTime":1}

**Comment by pipozzz** [comment]
I fixed that now, it’s fixed in v1.3.0 .
