### ISSUE TITLE
API File Upload, .txt download only.

### ISSUE THREAD

**Issue by nemoydev** [Pipoline/rocket-python#63]
When using: 
api.upload_file(room_id=id,file=files,description='some text',message='some text') the file is uploaded to respective room, and file format is correctly displayed. in example.  file.pdf
However, when downloading (through Rocket Chat on Windows), it automatically specifies the file as .txt and hereby changes the format. The save prompt does not recoqnice the fileformat: pdf or xlsm in example.
I can override the issue by first select file format of save prompt from .txt to *.* and then place the cursor on the filename and the press save button. 

on IOS Rocket Chat App, it can open the files correctly, but the app does not allow downloads. So it is unclear if the issue will also occur on IOS rocket chat app.

If I manually upload the same files by drag'n'drop into the same chat room I can download normally, internal and external from my network.

**Comment by pipozzz** [comment]
I found the problem, you are missing mime_type parameter in upload_file call, I will create PR with the possible fix, which I include in the next release, so we will guess the mimetype of file.
